"""Congressional-district rows: split from counties, or kept from the state.

`output/districts/<st>.csv` is the one table that is mostly derived. Three
states' files carry a district column and their adapters hand over
`DistrictDay` rows with `basis="reported"`; for everyone else -- and for
every PAST cycle, everywhere -- this module splits each county's published
daily figures across the districts the county touches and writes the result
with `basis="apportioned"`. See `schema.DistrictDay` for why past cycles are
never taken from the state even where the state labels them.

THE WEIGHTS. `data/crosswalk/county_cd_weights.csv` gives, for every county,
the share of its 2024 presidential vote cast inside each district it touches,
on the maps in force for 2026. It is generated by `scripts/build_cd_weights.py`
from the House model's county x district segments and vendored here, so the
pipeline owns its own reference data and CI needs no forecasts checkout. A
county wholly inside one district has one row of weight 1, which is most of
them; Wake County, NC has three.

WHAT A SPLIT IS NOT. An apportioned district row is an estimate of where a
county's early ballots came from, made by assuming they came from the county's
districts in the same proportion as its 2024 vote. That assumption is wrong
in every county whose districts turn out at different rates, and it is the
best available one. The page prints the basis beside every district figure;
this module's job is to make the arithmetic exact and the label honest, not to
make the estimate good.

TWO RULES THE ARITHMETIC KEEPS:

* District counts sum back to the county count to the ballot. Each county
  field is split by largest remainder, so 100 ballots over thirds is 34/33/33
  and never 33/33/33 or 34/34/34.
* THE BLANK RULE survives the split, both ways. A county that reports no
  party yields district party fields of None; and a district fed by two
  counties, one of which reports party and one of which does not, gets None
  too -- the sum over the county that reported is not the district's count,
  it is an unknown fraction of it.

`rebuild(out_dir, state, reported)` is the only writer. It reads the county
file ON DISK (so it runs after `publish_county_daily`), keeps every reported
row already in the district file, overlays the reported rows it was handed,
apportions every (cycle, day) that has no reported rows, and writes the whole
thing with `replace=True` -- the publisher's own rule for a derived table.
"""

from __future__ import annotations

import csv
import logging
from collections import defaultdict
from datetime import date
from functools import lru_cache
from pathlib import Path
from typing import Iterable, Sequence

from . import publish
from .calendar import CURRENT_CYCLE
from .schema import (
    BASIS_APPORTIONED, BASIS_REPORTED, CountyDay, DistrictDay, Provenance,
    district_row_to_dict,
)

log = logging.getLogger(__name__)

WEIGHTS_PATH = Path(__file__).resolve().parent.parent.parent / "data" / "crosswalk" / "county_cd_weights.csv"

#: The county fields that are split. `ballots_new` included: it is a count of
#: ballots like the others and the page's daily bars read it.
SPLIT_FIELDS = (
    "ballots_total", "ballots_new", "mail_returned", "inperson",
    "party_dem", "party_rep", "party_oth", "party_npa",
)

Weights = dict[str, dict[str, list[tuple[str, float]]]]


@lru_cache(maxsize=4)
def _load(path: str) -> Weights:
    out: Weights = defaultdict(lambda: defaultdict(list))
    with Path(path).open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            out[row["state"].upper()][row["county_fips"]].append(
                (row["cd_code"].upper(), float(row["weight"]))
            )
    return {st: dict(counties) for st, counties in out.items()}


def load_weights(path: Path | str | None = None) -> Weights:
    """{state: {county_fips: [(cd_code, weight), ...]}} from the vendored crosswalk."""
    return _load(str(path or WEIGHTS_PATH))


def covered(state: str, weights: Weights | None = None) -> bool:
    return state.upper() in (weights or load_weights())


def split_count(total: int | None, pieces: Sequence[tuple[str, float]]) -> dict[str, int | None]:
    """Split one count across districts by largest remainder.

    None in, None out for every district: a field the state did not report
    is not reported for any piece of it either.
    """
    if total is None:
        return {cd: None for cd, _ in pieces}
    total = int(total)
    raw = [(cd, total * w) for cd, w in pieces]
    floors: dict[str, int | None] = {cd: int(v) for cd, v in raw}
    short = total - sum(int(v or 0) for v in floors.values())
    # Hand the leftover ballots to the largest fractional parts, ties broken by
    # the district code so the answer is the same on every run.
    order = sorted(raw, key=lambda item: (-(item[1] - int(item[1])), item[0]))
    for cd, _ in order[:max(0, short)]:
        floors[cd] += 1
    return floors


def apportion(county_rows: Iterable[CountyDay], weights: Weights | None = None) -> list[DistrictDay]:
    """Split county rows into district rows, one per (cycle, day, district).

    Every row's `basis` is "apportioned" and its provenance is the provenance
    of the county rows it came from: the split is ours, the count is theirs.
    """
    weights = weights or load_weights()
    #: (cycle, state, day, cd) -> field -> [per-county contributions]
    sums: dict[tuple, dict[str, list[int | None]]] = defaultdict(lambda: defaultdict(list))
    prov: dict[tuple, Provenance | None] = {}
    skipped: dict[str, set[str]] = defaultdict(set)

    for row in county_rows:
        state = row.state.upper()
        pieces = weights.get(state, {}).get(row.county_fips)
        if not pieces:
            skipped[state].add(row.county_fips)
            continue
        for field in SPLIT_FIELDS:
            parts = split_count(getattr(row, field), pieces)
            for cd, value in parts.items():
                key = (int(row.cycle), state, row.day, cd)
                sums[key][field].append(value)
                prov.setdefault(key, row.provenance)

    for state, fips in sorted(skipped.items()):
        log.warning("%s: %d county row(s) not in the district crosswalk, not apportioned: %s",
                    state, len(fips), " ".join(sorted(fips)[:8]))

    out: list[DistrictDay] = []
    for key in sorted(sums, key=lambda k: (k[0], k[1], k[2].isoformat(), k[3])):
        cycle, state, day, cd = key
        fields: dict[str, int | None] = {}
        for field in SPLIT_FIELDS:
            parts = sums[key][field]
            # Blank if ANY contributing county left it blank -- see the module
            # docstring. A partial sum is not a smaller number, it is a wrong one.
            fields[field] = None if any(v is None for v in parts) else sum(int(v or 0) for v in parts)
        out.append(DistrictDay(
            cycle=cycle, state=state, cd_code=cd, day=day,
            basis=BASIS_APPORTIONED, provenance=prov[key], **fields,
        ))
    return out


# --------------------------------------------------------------------------
# Reading the county file back off disk
# --------------------------------------------------------------------------

def _num(cell: str | None) -> int | None:
    cell = (cell or "").strip()
    return int(float(cell)) if cell else None


def _county_rows(out_dir: Path, state: str) -> list[CountyDay]:
    path = Path(out_dir) / "counties" / f"{state.lower()}.csv"
    if not path.exists():
        return []
    rows: list[CountyDay] = []
    with path.open(newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            try:
                tier = int(r.get("source_tier") or 0)
            except ValueError:
                tier = 0
            if not tier:
                continue
            rows.append(CountyDay(
                cycle=int(r["cycle"]), state=r["state"].upper(),
                county_fips=r["county_fips"], county_name=r.get("county_name", ""),
                day=date.fromisoformat(r["date"]),
                provenance=Provenance(tier=tier, name=r.get("source_name", ""),
                                      retrieved_at=r.get("retrieved_at", "")),
                **{f: _num(r.get(f)) for f in SPLIT_FIELDS},
            ))
    return rows


def _reported_on_disk(out_dir: Path, state: str) -> list[dict[str, str]]:
    path = Path(out_dir) / "districts" / f"{state.lower()}.csv"
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as fh:
        return [r for r in csv.DictReader(fh) if r.get("basis") == BASIS_REPORTED]


# --------------------------------------------------------------------------
# The writer
# --------------------------------------------------------------------------

def rebuild(out_dir: Path, state: str, reported: Iterable[DistrictDay] = (),
            weights: Weights | None = None) -> dict | None:
    """Recompute `output/districts/<st>.csv` for one state and write it.

    Reported rows -- the ones on disk plus `reported` -- are kept as they are
    (incoming wins on a shared key). Every (cycle, day) with county rows and
    no reported rows is apportioned. Returns the publisher's summary, or None
    when there is nothing to write: no county file and no reported rows.
    """
    state = state.upper()
    out_dir = Path(out_dir)
    weights = weights or load_weights()

    # ⚠️ ONLY THE CURRENT CYCLE MAY BE REPORTED. A past cycle's reported rows
    # were labelled with that cycle's districts, and the map has moved since;
    # they are dropped here -- from disk and from `reported` alike -- and that
    # cycle is apportioned onto today's map below. This is what keeps the rule
    # true across cycles without any adapter knowing about it: in 2028 the
    # 2026 rows on disk become past rows and fall out on the first rebuild.
    kept: dict[tuple, dict[str, str]] = {}
    dropped = 0
    for r in _reported_on_disk(out_dir, state):
        if r.get("cycle") != str(CURRENT_CYCLE):
            dropped += 1
            continue
        kept[(r["cycle"], r["cd_code"], r["date"])] = r
    for row in reported:
        if row.basis != BASIS_REPORTED:
            raise ValueError(f"rebuild() takes reported rows only, got basis {row.basis!r}")
        if int(row.cycle) != CURRENT_CYCLE:
            dropped += 1
            continue
        d = district_row_to_dict(row)
        kept[(d["cycle"], d["cd_code"], d["date"])] = d
    if dropped:
        log.info("%s: %d reported district row(s) from a past cycle set aside; "
                 "past cycles are apportioned onto the current map", state, dropped)
    reported_days = {(k[0], k[2]) for k in kept}

    counties = [r for r in _county_rows(out_dir, state)
                if (str(r.cycle), r.day.isoformat()) not in reported_days]
    if not covered(state, weights) and counties:
        log.warning("%s: no district crosswalk for this state; only reported rows published", state)
        counties = []
    split = apportion(counties, weights) if counties else []

    rows = list(kept.values()) + [district_row_to_dict(r) for r in split]
    if not rows:
        return None
    return publish.publish_table(
        out_dir / "districts" / f"{state.lower()}.csv",
        publish.DISTRICT_DAILY_COLUMNS, publish.DISTRICT_KEY, rows, replace=True,
    )


def rebuild_all(out_dir: Path, states: Sequence[str] | None = None) -> list[dict]:
    """Rebuild every state that has a county file (or a district file already)."""
    out_dir = Path(out_dir)
    found: set[str] = set()
    for sub in ("counties", "districts"):
        d = out_dir / sub
        if d.exists():
            found.update(p.stem.upper() for p in d.glob("*.csv"))
    wanted = [s.upper() for s in states] if states else sorted(found)
    results = []
    for state in wanted:
        summary = rebuild(out_dir, state)
        if summary:
            results.append(summary)
    return results
